<a href="https://colab.research.google.com/github/rynwhd/Language-Models/blob/main/TextRank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
 import numpy as np
 import pandas as pd
 import string 
 import nltk
 nltk.download(['punkt','stopwords'])
 from nltk.corpus import stopwords
 from nltk.tokenize import sent_tokenize
 import textwrap
 import regex as re

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
!wget -nc https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv

--2023-02-23 05:08:23--  https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv
Resolving lazyprogrammer.me (lazyprogrammer.me)... 104.21.23.210, 172.67.213.166, 2606:4700:3030::ac43:d5a6, ...
Connecting to lazyprogrammer.me (lazyprogrammer.me)|104.21.23.210|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5085081 (4.8M) [text/csv]
Saving to: ‘bbc_text_cls.csv’

bbc_text_cls.csv    100%[===================>]   4.85M  --.-KB/s    in 0.02s   

2023-02-23 05:08:23 (195 MB/s) - ‘bbc_text_cls.csv’ saved [5085081/5085081]



In [4]:
df=pd.read_csv('bbc_text_cls.csv')

In [5]:
df.head()

text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [9]:
df=df[df.labels=='business']['text']

In [26]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [148]:
del len

In [51]:
def preprocess(x):
  x=x.lower()
  x=re.sub('''[!#$%&'()*+,-./:;<"=>?@[\]^_`{|}~]''','',x)
  x=[word for word in x.split(' ') if not any(x.isdigit() for c in word)]
  x=[word for word in x if word not in stopwords.words('english')]
  return ' '.join(x).strip()

In [30]:
df.head()

0    Ad sales boost Time Warner profit\n\nQuarterly...
1    Dollar gains on Greenspan speech\n\nThe dollar...
2    Yukos unit buyer faces loan claim\n\nThe owner...
3    High fuel prices hit BA's profits\n\nBritish A...
4    Pernod takeover talk lifts Domecq\n\nShares in...
Name: text, dtype: object

In [14]:
df.iloc[10]

"Ask Jeeves tips online ad revival\n\nAsk Jeeves has become the third leading online search firm this week to thank a revival in internet advertising for improving fortunes.\n\nThe firm's revenue nearly tripled in the fourth quarter of 2004, exceeding $86m (£46m). Ask Jeeves, once among the best-known names on the web, is now a relatively modest player. Its $17m profit for the quarter was dwarfed by the $204m announced by rival Google earlier in the week. During the same quarter, Yahoo earned $187m, again tipping a resurgence in online advertising.\n\nThe trend has taken hold relatively quickly. Late last year, marketing company Doubleclick, one of the leading providers of online advertising, warned that some or all of its business would have to be put up for sale. But on Thursday, it announced that a sharp turnaround had brought about an unexpected increase in profits. Neither Ask Jeeves nor Doubleclick thrilled investors with their profit news, however. In both cases, their shares fe

In [20]:
def wrap(text):
  return textwrap.fill(text,fix_sentence_endings=True,replace_whitespace=False)

In [126]:
doc=df.iloc[12]

In [127]:
wrap(doc)

"Peugeot deal boosts Mitsubishi\n\nStruggling Japanese car maker\nMitsubishi Motors has struck a deal to supply French car maker Peugeot\nwith 30,000 sports utility vehicles (SUV).\n\nThe two firms signed a\nMemorandum of Understanding, and say they expect to seal a final\nagreement by Spring 2005. The alliance comes as a badly-needed boost\nfor loss-making Mitsubishi, after several profit warnings and poor\nsales.  The SUVs will be built in Japan using Peugeot's diesel engines\nand sold mainly in the European market.  Falling sales have left\nMitsubishi Motors with underused capacity, and the production deal\nwith Peugeot gives it a chance to utilise some of it.\n\nIn January,\nMitsubishi Motors issued its third profits warning in nine months, and\ncut its sales forecasts for the year to March 2005. Its sales have\nslid 41% in the past year, catalysed by the revelation that the\ncompany had systematically been hiding records of faults and then\nsecretly repairing vehicles.  As a resul

In [128]:
sents=doc.split('\n\n')

In [129]:
sents

['Peugeot deal boosts Mitsubishi',
 'Struggling Japanese car maker Mitsubishi Motors has struck a deal to supply French car maker Peugeot with 30,000 sports utility vehicles (SUV).',
 "The two firms signed a Memorandum of Understanding, and say they expect to seal a final agreement by Spring 2005. The alliance comes as a badly-needed boost for loss-making Mitsubishi, after several profit warnings and poor sales. The SUVs will be built in Japan using Peugeot's diesel engines and sold mainly in the European market. Falling sales have left Mitsubishi Motors with underused capacity, and the production deal with Peugeot gives it a chance to utilise some of it.",
 "In January, Mitsubishi Motors issued its third profits warning in nine months, and cut its sales forecasts for the year to March 2005. Its sales have slid 41% in the past year, catalysed by the revelation that the company had systematically been hiding records of faults and then secretly repairing vehicles. As a result, the Japane

In [130]:
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics.pairwise import cosine_similarity

In [131]:
featurizer=TfidfVectorizer(analyzer=preprocess)

In [132]:
X=featurizer.fit_transform(sents)

In [133]:
S=cosine_similarity(X)

In [140]:
S

array([[0.28945261, 0.23185784, 0.24348059, 0.23520896],
       [0.21740393, 0.27140827, 0.25215072, 0.25903708],
       [0.2245818 , 0.24804177, 0.2669855 , 0.26039094],
       [0.21713795, 0.25503408, 0.26061388, 0.26721409]])

In [141]:
S/=S.sum(axis=1,keepdims=True) #normalization of similarity matrix, each row sums. to 1 S[0]=1

In [149]:
#Uniform Trans Matrix
U=np.ones_like(S)/len(S)
#The uniform matrix has 1/M overall where M is the doc len

In [150]:
U

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

In [151]:
from ast import USub
#smoothing similarity matrix
factor=.15
A=(1-factor)*S+factor*U

In [152]:
A

array([[0.28353472, 0.23457916, 0.2444585 , 0.23742761],
       [0.22229334, 0.26819703, 0.25182812, 0.25768152],
       [0.22839453, 0.2483355 , 0.26443767, 0.2588323 ],
       [0.22206726, 0.25427897, 0.2590218 , 0.26463197]])

In [153]:
eigenvals,eigenvecs=np.linalg.eig(S.T)

In [154]:
eigenvals

array([1.        , 0.07061507, 0.00501872, 0.01942667])

In [155]:
eigenvecs[:]

array([[ 0.47213188,  0.8591465 , -0.06717146, -0.08034596],
       [ 0.50352116, -0.34339335,  0.23173749, -0.75980454],
       [ 0.51186228, -0.18389132,  0.59898226,  0.59800101],
       [ 0.51142441, -0.33186183, -0.76354828,  0.24214949]])

In [156]:
eigenvecs[:,0] # because np stores values as columns and not rows

array([0.47213188, 0.50352116, 0.51186228, 0.51142441])

In [157]:
scores=eigenvecs[:,0]/eigenvecs[:,0].sum()

In [158]:
sort_idx=np.argsort(-scores)

In [159]:
for i in sort_idx[:5]:
  print(wrap('%.2f: %s'%(scores[i],sents[i])))

0.26: The two firms signed a Memorandum of Understanding, and say they
expect to seal a final agreement by Spring 2005. The alliance comes as
a badly-needed boost for loss-making Mitsubishi, after several profit
warnings and poor sales.  The SUVs will be built in Japan using
Peugeot's diesel engines and sold mainly in the European market.
Falling sales have left Mitsubishi Motors with underused capacity, and
the production deal with Peugeot gives it a chance to utilise some of
it.
0.26: In January, Mitsubishi Motors issued its third profits warning
in nine months, and cut its sales forecasts for the year to March
2005. Its sales have slid 41% in the past year, catalysed by the
revelation that the company had systematically been hiding records of
faults and then secretly repairing vehicles.  As a result, the
Japanese car maker has sought a series of financial bailouts.  Last
month it said it was looking for a further 540bn yen ($5.2bn; £2.77bn)
in fresh financial backing, half of it fro